### PR TITLE
Fixed Datetime issues

### PR DESCRIPTION
**Pull request by scheb**
I've fixed serveral issues regarding DateTime objects. First, you've forgotten leading backslashes in your method signatures. Second, I've found a syntax error, when it's formatting the until timestamp. Would you please merge?

### CODE REVIEW

**Comment by scheb** [comment]
Had to make some more changes. The library did not support different date formats. Now you can define a datetime granularity in the Client constructor. If not given, it tries to fetch it from the Identify API method.

**Comment by caseyamcl** [comment]
Hi @scheb .. Thank you for fixing these syntax errors!  I will merge this pull request, and release a new version; but, it would be useful to have some unit tests too

Do you have time to add unit tests for the granularity class and the corrected endpoint method?  If not, I can get to it soon.

**Comment by scheb** [comment]
Added test cases, but some methods are still untested. I'd like to have full coverage for the Client and RecordIterator classes, because those are the core classes of the library. Will continue tomorrow, so please don't merge yet.

Btw: For some reason I cannot access http://nsdl.org/oai which you're using for your tests. Any idea?

**Comment by caseyamcl** [comment]
@scheb, yeah I noticed yesterday that the http://nsdl.org/oai endpoint is not working.  If you look at my latest commits from last night, you'll see I updated the `EndpointCurlTest` to use http://openscholarship.wustl.edu/do/oai/ instead.

If you pull or rebase with those commits, the tests should succeed again.

**Comment by scheb** [comment]
Rebased and ready for merge :)

**Comment by scheb** [comment]
Btw: Would you please remove the `.idea` folder from the repository? Your personal PHPStorm confguration shouldn't be part of a repository. It conflicts with my own PHPStorm all the time. If you need to ship it, I'd suggest to name it differently, e.g. `.idea.sample`. Thanks!

**Comment by caseyamcl** [comment]
@scheb Ah, yes, I should probably remove that :).  Now that your pull requests are merged, I am going to put out a new release today, and will remove `.idea` before then.

**Pull request merged**
