### PR TITLE
Test request URL being build correction

### PR DESCRIPTION
**Pull request by scheb**
Test case for caseyamcl/phpoaipmh#20

### CODE REVIEW

**Comment by scheb** [comment]
And would be please create a new release, so that I can require a stable version :)

**Comment by caseyamcl** [comment]
Hi @scheb.  Looks good.  I'll pull and tag a release later today.

**Comment by caseyamcl** [comment]
Hi @scheb -- Just tagged Version 2.3

**Comment by scheb** [comment]
Thanks! :)

**Pull request merged**
