### PR TITLE
#26 Fix namespace lack for children.

### PR DESCRIPTION
**Pull request by vbeauvivre**
Sorry for dirtey code (work on strings), but it seems SimpleXML does not allow us to add namespace definition. Its addAttribute method remove anything before «:».

### CODE REVIEW

**Comment by vbeauvivre** [comment]
See #26

**Comment by vbeauvivre** [comment]
Oups. I didn’t expect my last commit on composer.json project’s name to appear on PR.
How can I exclude it ? I make pull request from last commit hash that I want to propose ?

**Comment by caseyamcl** [comment]
Hey @vbeauvivre  - I apologize for the delay in response - I've been out with other business lately, and am getting back around to this library today. I promise this is not abandonware :)

I looked at your issue and your pull request.  I think I will merge it with some additional tweaks:

1. Remove commit 68ea627 from the PR (see http://goo.gl/xl3YaO for help or Google "remove commit from pull request")
2. Refactor the lines you added to `RecordIterator.php` (lines 171 - 182) into their own protected method, and ensure you add DocBlock (with @author attribute)
3. If you're able, please add a unit test based on the example XML you provided in your issue.  If you don't know how to do that, then let me know, and I can help.

Thanks very much for identifying this and contributing a solution!

**Comment by vbeauvivre** [comment]
Great to ear it !
I will work on that today.

**Comment by vbeauvivre** [comment]
See #30

**Pull request closed without merging**
